// Code generated by gengo:enum DO NOT EDIT.
package model

import (
	bytes "bytes"
	driver "database/sql/driver"
	errors "errors"
	fmt "fmt"

	enumeration "github.com/octohelm/enumeration/pkg/enumeration"
	pkgscanner "github.com/octohelm/enumeration/pkg/scanner"
)

var InvalidColor = errors.New("invalid Color")

func (Color) EnumValues() []any {
	return []any{
		COLOR__RED, COLOR__GREEN, COLOR__BLUE,
	}
}

func (v Color) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

func (v *Color) UnmarshalText(data []byte) error {
	vv, err := ParseColorFromString(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

func ParseColorFromString(s string) (Color, error) {
	switch s {
	case "100":
		return COLOR__RED, nil
	case "200":
		return COLOR__GREEN, nil
	case "300":
		return COLOR__BLUE, nil

	default:
		var i Color
		_, err := fmt.Sscanf(s, "UNKNOWN_%d", &i)
		if err == nil {
			return i, nil
		}
		return COLOR_UNKNOWN, InvalidColor
	}
}

func (v Color) IsZero() bool {
	return v == COLOR_UNKNOWN
}

func (v Color) String() string {
	switch v {
	case COLOR__RED:
		return "100"
	case COLOR__GREEN:
		return "200"
	case COLOR__BLUE:
		return "300"
	case COLOR_UNKNOWN:
		return "0"

	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

func ParseColorLabelString(label string) (Color, error) {
	switch label {
	case "100":
		return COLOR__RED, nil
	case "200":
		return COLOR__GREEN, nil
	case "300":
		return COLOR__BLUE, nil

	default:
		return COLOR_UNKNOWN, InvalidColor
	}
}

func (v Color) Label() string {
	switch v {
	case COLOR__RED:
		return "100"
	case COLOR__GREEN:
		return "200"
	case COLOR__BLUE:
		return "300"

	default:
		return fmt.Sprint(v)
	}
}

func (v Color) Value() (driver.Value, error) {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}
	return int64(v) + int64(offset), nil
}

func (v *Color) Scan(src any) error {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}

	i, err := pkgscanner.ScanIntEnumStringer(src, offset)
	if err != nil {
		return err
	}
	*v = Color(i)
	return nil
}

var InvalidFlag = errors.New("invalid Flag")

func (Flag) EnumValues() []any {
	return []any{
		FLAG__READ, FLAG__WRITE, FLAG__EXEC,
	}
}

func (v Flag) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

func (v *Flag) UnmarshalText(data []byte) error {
	vv, err := ParseFlagFromString(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

func ParseFlagFromString(s string) (Flag, error) {
	switch s {
	case "READ":
		return FLAG__READ, nil
	case "WRITE":
		return FLAG__WRITE, nil
	case "EXEC":
		return FLAG__EXEC, nil

	default:
		var i Flag
		_, err := fmt.Sscanf(s, "UNKNOWN_%d", &i)
		if err == nil {
			return i, nil
		}
		return FLAG_NONE, InvalidFlag
	}
}

func (v Flag) IsZero() bool {
	return v == FLAG_NONE
}

func (v Flag) String() string {
	switch v {
	case FLAG__READ:
		return "READ"
	case FLAG__WRITE:
		return "WRITE"
	case FLAG__EXEC:
		return "EXEC"
	case FLAG_NONE:
		return "0"

	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

func ParseFlagLabelString(label string) (Flag, error) {
	switch label {
	case "READ":
		return FLAG__READ, nil
	case "WRITE":
		return FLAG__WRITE, nil
	case "EXEC":
		return FLAG__EXEC, nil

	default:
		return FLAG_NONE, InvalidFlag
	}
}

func (v Flag) Label() string {
	switch v {
	case FLAG__READ:
		return "READ"
	case FLAG__WRITE:
		return "WRITE"
	case FLAG__EXEC:
		return "EXEC"

	default:
		return fmt.Sprint(v)
	}
}

func (v Flag) Value() (driver.Value, error) {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}
	return int64(v) + int64(offset), nil
}

func (v *Flag) Scan(src any) error {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}

	i, err := pkgscanner.ScanIntEnumStringer(src, offset)
	if err != nil {
		return err
	}
	*v = Flag(i)
	return nil
}

var InvalidGender = errors.New("invalid Gender")

func (Gender) EnumValues() []any {
	return []any{
		GENDER__MALE, GENDER__FEMALE,
	}
}

func (v Gender) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

func (v *Gender) UnmarshalText(data []byte) error {
	vv, err := ParseGenderFromString(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

func ParseGenderFromString(s string) (Gender, error) {
	switch s {
	case "MALE":
		return GENDER__MALE, nil
	case "FEMALE":
		return GENDER__FEMALE, nil

	default:
		var i Gender
		_, err := fmt.Sscanf(s, "UNKNOWN_%d", &i)
		if err == nil {
			return i, nil
		}
		return GENDER_UNKNOWN, InvalidGender
	}
}

func (v Gender) IsZero() bool {
	return v == GENDER_UNKNOWN
}

func (v Gender) String() string {
	switch v {
	case GENDER__MALE:
		return "MALE"
	case GENDER__FEMALE:
		return "FEMALE"
	case GENDER_UNKNOWN:
		return "UNKNOWN"

	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

func ParseGenderLabelString(label string) (Gender, error) {
	switch label {
	case "男":
		return GENDER__MALE, nil
	case "女":
		return GENDER__FEMALE, nil

	default:
		return GENDER_UNKNOWN, InvalidGender
	}
}

func (v Gender) Label() string {
	switch v {
	case GENDER__MALE:
		return "男"
	case GENDER__FEMALE:
		return "女"

	default:
		return fmt.Sprint(v)
	}
}

func (v Gender) Value() (driver.Value, error) {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}
	return int64(v) + int64(offset), nil
}

func (v *Gender) Scan(src any) error {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}

	i, err := pkgscanner.ScanIntEnumStringer(src, offset)
	if err != nil {
		return err
	}
	*v = Gender(i)
	return nil
}

var InvalidGenderExt = errors.New("invalid GenderExt")

func (GenderExt) EnumValues() []any {
	return []any{
		GENDER_EXT__FEMALE, GENDER_EXT__MALE,
	}
}

func ParseGenderExtLabelString(label string) (GenderExt, error) {
	switch label {
	case "女":
		return GENDER_EXT__FEMALE, nil
	case "男":
		return GENDER_EXT__MALE, nil

	default:
		return *new(GenderExt), InvalidGenderExt
	}
}

func (v GenderExt) Label() string {
	switch v {
	case GENDER_EXT__FEMALE:
		return "女"
	case GENDER_EXT__MALE:
		return "男"

	default:
		return fmt.Sprint(v)
	}
}

var InvalidToken = errors.New("invalid Token")

func (Token) EnumValues() []any {
	return []any{
		EOF, COMMENT,
	}
}

func (v Token) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

func (v *Token) UnmarshalText(data []byte) error {
	vv, err := ParseTokenFromString(string(bytes.ToUpper(data)))
	if err != nil {
		return err
	}
	*v = vv
	return nil
}

func ParseTokenFromString(s string) (Token, error) {
	switch s {
	case "EOF":
		return EOF, nil
	case "COMMENT":
		return COMMENT, nil

	default:
		var i Token
		_, err := fmt.Sscanf(s, "UNKNOWN_%d", &i)
		if err == nil {
			return i, nil
		}
		return ILLEGAL, InvalidToken
	}
}

func (v Token) IsZero() bool {
	return v == ILLEGAL
}

func (v Token) String() string {
	switch v {
	case EOF:
		return "EOF"
	case COMMENT:
		return "COMMENT"
	case ILLEGAL:
		return "ILLEGAL"

	default:
		return fmt.Sprintf("UNKNOWN_%d", v)
	}
}

func ParseTokenLabelString(label string) (Token, error) {
	switch label {
	case "EOF":
		return EOF, nil
	case "COMMENT":
		return COMMENT, nil

	default:
		return ILLEGAL, InvalidToken
	}
}

func (v Token) Label() string {
	switch v {
	case EOF:
		return "EOF"
	case COMMENT:
		return "COMMENT"

	default:
		return fmt.Sprint(v)
	}
}

func (v Token) Value() (driver.Value, error) {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}
	return int64(v) + int64(offset), nil
}

func (v *Token) Scan(src any) error {
	offset := 0
	if o, ok := any(v).(enumeration.DriverValueOffset); ok {
		offset = o.Offset()
	}

	i, err := pkgscanner.ScanIntEnumStringer(src, offset)
	if err != nil {
		return err
	}
	*v = Token(i)
	return nil
}
