export INFRA_CLI_DEBUG := "1"

# 整理依赖
[group('env')]
[no-cd]
dep:
    go mod tidy

# 更新依赖
[group('env')]
[no-cd]
update:
    go get -u ./...

# 运行测试（默认覆盖全部包）
[group('test')]
[no-cd]
test path='./...' *args:
    go test -count=1 -failfast {{ args }} {{ path }}

# 格式化
[group('fmt')]
[no-cd]
fmt path='./...':
    go tool fmt {{ path }}

# 代码生成
[group('build')]
[no-cd]
gen path='./...' *args:
    go generate {{ args }} {{ path }}
